# Taken largely from:
# https://medium.com/@ayeshasilvia/testing-ansible-playbook-in-a-docker-container-21628e9ee256

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y openssh-server sudo python unzip python-pip
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Install testinfra
RUN pip install testinfra

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
